#!/usr/bin/env bash
set -euo pipefail

echo "==> netprobe devcontainer setup"

# Ensure Conan home points to workspace-local cache
export CONAN_HOME=/workspace/.conan2

# Detect/refresh Conan profile
conan profile detect --force

# Allow Conan to install system packages inside the container
cat >> "${CONAN_HOME}/profiles/default" << 'EOF'

[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
EOF

# Install dependencies and configure (Debug build for development)
echo "==> Installing Conan dependencies..."
conan install . \
    --output-folder=build/Debug \
    --build=missing \
    --settings=build_type=Debug

# Configure CMake (uses the preset generated by Conan)
echo "==> Configuring CMake..."
cmake --preset conan-debug 2>/dev/null || \
cmake -S . -B build/Debug \
    -DCMAKE_TOOLCHAIN_FILE=build/Debug/conan_toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -G Ninja

# Symlink compile_commands.json to project root for clangd
ln -sf build/Debug/compile_commands.json compile_commands.json 2>/dev/null || true

echo ""
echo "==> Done. Build with:"
echo "    cmake --build build/Debug"
echo "    ctest --test-dir build/Debug"
